# Generated by Django 6.0.2 on 2026-02-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcats', to='core.category'),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
