# Generated by Django 6.0.2 on 2026-02-18 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_feedback_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
