# Generated by Django 6.0.2 on 2026-02-18 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_buildrequest_created_at_buildrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
