# Generated by Django 6.0.2 on 2026-02-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_options_alter_projectmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmedia',
            options={},
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.URLField(max_length=500),
        ),
    ]
