# Generated by Django 6.0.2 on 2026-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_projectmedia_options_alter_projectmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='client_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
